spring:
    datasource:
        url: jdbc:mysql://awseb-e-bzrrgmhudv-stack-awsebrdsdatabase-fw1brlihrekj.ckac3747cbzm.ap-northeast-2.rds.amazonaws.com/board?useSSL=false&serverTimezone=Asia/Seoul
        username: fastcam
        password: fastcam1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
